name: Build and deploy the front-end module
on:
  push:
    branches:
      - master

jobs:
  deploy-front-end:
    name: Deploy front-end to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: |
          npm install
      - name: Build the front-end module
        env:
          CI: false
        run: |
          npm run build
          npm audit fix
      - name: Create the publishing branch if it doesn't exist
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'public'

      - name: Push the built files to the publishing branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: public
          FOLDER: front-end/build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Publishing commit: {sha}\nDescription: {msg}"